services:
  # db:
  #   image: postgres:latest
  #   container_name: group-allocator
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password1234
  #     POSTGRES_DB: GroupAllocator
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  backend:
    image: ghcr.io/oliverw10/group-allocator:main
    container_name: group-allocator-backend
    restart: unless-stopped
    ports:
      - '3000:8080'
    # depends_on:
    #   - db
    volumes:
      - ./appsettings.json:/App/appsettings.json
