START TRANSACTION;
CREATE TABLE "ClientLimits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" integer NOT NULL,
    "MinProjects" integer NOT NULL,
    "MaxProjects" integer NOT NULL,
    "SolveRunId" integer NOT NULL,
    CONSTRAINT "PK_ClientLimits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClientLimits_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ClientLimits_SolveRuns_SolveRunId" FOREIGN KEY ("SolveRunId") REFERENCES "SolveRuns" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ClientLimits_ClientId" ON "ClientLimits" ("ClientId");

CREATE INDEX "IX_ClientLimits_SolveRunId" ON "ClientLimits" ("SolveRunId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250722111120_AddClientLimits', '9.0.1');

COMMIT;

