name: .NET Build

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!main'

defaults:
  run:
    working-directory: backend

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Install tool dependencies
        run: dotnet tool restore
      - name: Build
        run: dotnet build --no-restore
